# -*- coding: utf-8 -*-
"""RockPaperScissors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f-8tVt4NhsLr64A9ibFF7vCuYGV6PBgy
"""

# Rock paper scissors game

import random

# Create a function to generate the computer's choice
def computer_choice():
    choices = ["rock", "paper", "scissors"]
    return random.choice(choices)

# Create a function to determine the winner
def determine_winner(player, computer):
    if player == computer:
        return "It's a tie!"
    elif player == "rock" and computer == "scissors":
        return "Player wins!"
    elif player == "paper" and computer == "rock":
        return "Player wins!"
    elif player == "scissors" and computer == "paper":
        return "Player wins!"
    else:
        return "Computer wins!"

# Create a while loop to play the game
while True:
    # Get the player's choice
    player = input("Rock, paper, or scissors? ")

    # Generate the computer's choice
    computer = computer_choice()

    # Determine the winner
    result = determine_winner(player, computer)

    # Print the result
    print("Player chose", player)
    print("Computer chose", computer)
    print(result)